name: (Test) Mirror all 7Ji repo packages to GitHub Release (AArch64)

# Controls when the workflow will run
on:
  # Runs on pushes targeting the default branch
  #push:
    #branches: ["main"]
  # Run the workflow every Night at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Download repository archives
        uses: robinraju/release-downloader@v1
        with:
          repository: '7Ji/archrepo'
          tag: 'aarch64'
          out-file-path: 'output'
          fileName: '*.tar.zst'

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "output/*"
            tag: "aarch64"
            makeLatest: false
            allowUpdates: true
            removeArtifacts: true
            omitBody: true
