name: (Test) Mirror all 7Ji repo packages to GitHub Release (AArch64)

# Controls when the workflow will run
on:
  # Runs on pushes targeting the default branch
  #push:
    #branches: ["main"]
  # Run the workflow every Night at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  configure:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: 1usOS/PKGBUILDs
      - name: Set matrix data
        id: set-matrix
        run: |
          sudo snap install yq
          echo "matrix=$(yq eval '.packages | to_entries | map(.key) | join(",")' rockchip/mirror.yaml)" >> $GITHUB_OUTPUT
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Mirror Packages
    permissions:
      contents: write
    strategy:
      matrix:
        package: ${{ needs.configure.outputs.matrix }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Preparing
        run: |
          echo "hello world"
